### ISSUE TITLE
Why the data path is to real images?    'gen-nuscnes-train-infos.pkl'

### ISSUE THREAD

**Issue by kjkimnb** [wenyuqing/panacea#14]
Follow your instruction, the gen image will be in the path ./data/nuscenes/gen-nuscenes-train
But the data path in 'gen-nuscnes-train-infos.pkl' is to ./data/nuscenes/samples/, which contains real images.
![20240510-160821](https://github.com/wenyuqing/panacea/assets/42375495/a575b302-3a2f-482f-b2b0-e24576f7148e)
Is that mean you train the model on the real data?
Also, I find 8 pictures in the fold, which one should be used for training?

**Comment by wenyuqing** [comment]
Hi， the path in the gen-nuscnes-train-infos.pkl is the original path of nuscenes, but in training the root path will be replaced by /data/Dataset/nuScenes/gen-nuscenes-train/, so it actually uses Gen-nuScenes rather than real nuScenes. Each folder contains a video with 8 consecutive frames.  You should use all 8 frames for training.

**Comment by kjkimnb** [comment]
Oh, I have found the code for replacing in nuscenes_dataset.py
Thank you for your prompt reply !
