### ISSUE TITLE
A issue about "nuscenes2d_ego_temporal_infos_train.pkl"

### ISSUE THREAD

**Issue by fayewong666999** [wenyuqing/panacea#28]
It's a great job. I have a question, in this work, you use the file "nuscenes2d_ego_temporal_infos_train.pkl", and I observe that the "gt_boxes" in this file are different from the gt_boxes in the "nuscenes2d_temporal_infos_train.pkl" file, is it because the coordinates in the two are in different coordinate systems?  Or does the gt_boxes representation in the ego coordinate system have a better advantage？ Thank you!

**Comment by ZhiyingDu** [comment]
> It's a great job. I have a question, in this work, you use the file "nuscenes2d_ego_temporal_infos_train.pkl", and I observe that the "gt_boxes" in this file are different from the gt_boxes in the "nuscenes2d_temporal_infos_train.pkl" file, is it because the coordinates in the two are in different coordinate systems? Or does the gt_boxes representation in the ego coordinate system have a better advantage？ Thank you!

Hello, i am fresh to nuscenes. Do you know how to generation "nuscenes2d_ego_temporal_infos_train.pkl"? I don't see any related code about it in this rep and [StreamPETR](https://github.com/exiawsh/StreamPETR).

**Comment by wenyuqing** [comment]
Sorry for the late reply! The **nuscenes2d_ego_temporal_infos_train.pkl** file uses the ego coordinate system, while **nuscenes2d_temporal_infos_train.pkl** uses the lidar coordinate system. The lidar and ego systems differ by a transformation. The choice to use **nuscenes2d_ego_temporal_infos_train.pkl** with the ego coordinate system is because it also includes lane lines, so both the lane lines and ground truth boxes are in the ego system. Then, the same transformation is applied to project them into the camera coordinate system. Since the generation is done in the image space, it doesn’t matter which coordinate system’s annotations are used for training, as everything will ultimately be generated in the image space.
